### ISSUE TITLE
branch renderer are trunck

### ISSUE THREAD

**Issue by tpabst** [deuill/grawkit#10]
Hello there,

I try grawkit tool and get a display issue. the text are truncated at the end ! if I use small text the issue is the the same.
<img width="183" alt="grawkit display issue" src="https://user-images.githubusercontent.com/1242387/117018830-29039e00-acf5-11eb-923a-cc1d571e62c8.png">

Did you have an idea ?

**Comment by deuill** [comment]
I wonder if this might be related to the font being chosen -- where are you having this render? Does it look OK in your browser?

**Comment by tpabst** [comment]
Quick answer !
I render this myself on an ubuntu 16.04 juste by typing
`grawkit myfile.txt > myfile.svg`
Can we choose the font ?

EDIT: I use ristretto 0.8.0 (xfce default image viewer) to display it, and The display looks good when I open it with firefox

**Comment by deuill** [comment]
Ah, an issue with Ristretto, then. The font used is defined here:

https://github.com/deuill/grawkit/blob/5500c9c66786557ab782ea81b51b82b2f5982876/grawkit#L299

We assume that the font is monospace and that the height is approximately twice the size of the width (which generally holds true for monospace fonts); unfortunately this isn't always true, even when rendered correctly.

**Comment by tpabst** [comment]
Ok, so I asume it will be the case for each viewer using the wring font.
Same issue with:
* gnome Image Viewer 3.18.2 (eye of gnome)
* Inkscape
* gimp
* ...

Ok with:
 * Firefox
 * Chrome

So it will be the case if the font isn't monospace. 
Ok good to know.

Thanks for the help

**Comment by tpabst** [comment]
So install the right font fix the issue
```
sudo apt-get install fonts-inconsolata -y
sudo fc-cache -fv
```
