### ISSUE TITLE
Allow `main` branch instead of `master` ?

### ISSUE THREAD

**Issue by bew** [deuill/grawkit#12]
TSIA, right now the main branch is called `master`, when we do `git checkout main` we get the error `No branch with name 'main'`

**Comment by deuill** [comment]
Hi, I've pushed a fix with the ability to specify the default branch name, among other things -- use the `--default-branch=main` command-line option to change the default branch name to `main`.

**Comment by bew** [comment]
Woooh the new configuration is nice :heart_eyes:

I originally hit the master/main issue on the online version, do you think you'll allow changing the branch there? (and maybe expose other configs?)

**Comment by deuill** [comment]
I've wanted to do this for a while, and since you ask nicely... I'll take a look at implementing it!
