### ISSUE TITLE
Render commit messages as labels

### ISSUE THREAD

**Issue by deuill** [deuill/grawkit#2]
Currently, commit messages are allowed via `-m` and stored, but not rendered in any way. Render these as labels after the branch/tag labels.

**Comment by fthomasfr** [comment]
Just for information, I have updated your script in my fork to render the commit labels: https://github.com/fthomasfr/grawkit/blob/roadmap/tests/explanation.svg

**Comment by deuill** [comment]
That looks awesome! I'll look to incorporate these changes in once I've got some time on my hands.
