### ISSUE TITLE
How to use this amazing tool ?

### ISSUE THREAD

**Issue by KROSF** [deuill/grawkit#5]
I'm trying to use it for a homework about git.
Can you make me a simple example how to run this tool ?
Thanks.

**Comment by KROSF** [comment]
I found the way to use it.

**Comment by Wonskcalb** [comment]
Please enlighten us @KROSF

**Comment by deuill** [comment]
I'll expand the README, but you can use this tool by feeding it newline-separated `git` commands, like you would pass to the command-line. For instance, the following command line will give you the resulting SVG:

```sh
$ cat example.txt
git commit -m "Adding a new commit"
git commit
$ cat example.txt | ./grawkit > example.svg
```

**example.svg**
![example.svg](https://rawgit.com/deuill/grawkit/b5708197cfcc526498053f9a07565a2d77615054/tests/02-master.svg)

Not all commands are supported, of course, and some don't make much sense (especially those that either don't affect the state of the tree, such as `git log`, or those that change existing history, such as `git rebase`.
