### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by NickdeK** [deuill/grawkit#6]
Looks great but it's really unclear to me how to use this tool. I tried adding a .md file and running the `make doc` command, but it doesn't seem to do anything. `make help` also isn't helping.

If you could give some basic instructions I'm willing to write more extensively and do a pull request to improve the readme :)

**Comment by NickdeK** [comment]
Ah apologies, it seems that my questions was already asked a few days ago: https://github.com/deuill/grawkit/issues/5

**Comment by deuill** [comment]
No worries, I'll add instructions into the README.
