### ISSUE TITLE
Unable to run it on Mac

### ISSUE THREAD

**Issue by martinstuga** [deuill/grawkit#7]
I got no error messages, but it generates nothing.

Any tips?

**Comment by deuill** [comment]
I think Mac OS X either bundles older versions of GNU Awk (`gawk`), or has just plain BSD Awk, and unfortunately we depend on GNU Awk extension at the moment.

If you have `brew` installed, you should be able to get `gawk` installed using:

```
brew install gawk
```

I'm working on getting an online playground going so you won't have to do this in the future.

**Comment by martinstuga** [comment]
Thank you for the quick answer.
I have installed gawk with brew before my first message.

Yeah, having it online would be amazing.

For now, I'll try it with docker.

**Comment by deuill** [comment]
Ah, apologies. I'll give this a whirl on a Mac OS X machine if I can get my hands on one, but yeah, Docker is probably your best bet at the moment. No idea why this isn't returning an error.

**Comment by martinstuga** [comment]
In a ubuntu docker I get the same… no output.

How should the output be? A file? Should I redirect the output to a file?

Thank you.

**Comment by deuill** [comment]
You should be able to either pass input in via standard input, or point `grawkit` to a file. The simplest example is:

```
$ printf "git commit" | ./grawkit
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-10 -10 112 120">
<more SVG output>
</svg>
```

You can then redirect to a file etc. as per usual. The README file explains this in a bit more detail.

**Comment by martinstuga** [comment]
Thank you!

It worked in docker, but have to change the first script line to:

#!/usr/bin/awk -f

Great tool!

Thanks

**Comment by deuill** [comment]
Nice, thanks! I'll see about getting this working with POSIX Awk as well.

**Comment by deuill** [comment]
Grawkit is now POSIX-compatible, and should work with whatever AWK implementation is included in Mac OS X. I'll close this, as the playground is still a ways away, feel free to re-open if you find any additional issues.

**Comment by martinstuga** [comment]
Thank you so much.

It works well! Great work!

**Comment by deuill** [comment]
This is now available on https://grawkit.deuill.org
